"""add meeting processing fields

Revision ID: eac16ff371f9
Revises: 0004d0d18a3d
Create Date: 2026-02-25 20:16:05.684393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac16ff371f9'
down_revision: Union[str, Sequence[str], None] = '0004d0d18a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('audio_path', sa.String(length=500), nullable=True))
    op.add_column('meetings', sa.Column('mime_type', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('meetings', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'processed_at')
    op.drop_column('meetings', 'error_message')
    op.drop_column('meetings', 'summary')
    op.drop_column('meetings', 'transcript')
    op.drop_column('meetings', 'file_size_bytes')
    op.drop_column('meetings', 'mime_type')
    op.drop_column('meetings', 'audio_path')
    op.drop_column('meetings', 'original_filename')
    # ### end Alembic commands ###
